"""GitHub Publisher: ブランチ作成・PR 作成。全チェック合格時のみ呼ばれる。"""
from __future__ import annotations

import os
import re
import subprocess
from pathlib import Path

from unicorn_agent.state import AgentState


def _sanitize_branch_name(name: str) -> str:
    """ブランチ名に使えるようにサニタイズ。"""
    s = re.sub(r"[^a-zA-Z0-9/_.-]", "-", name)[:80]
    return s.strip("-") or "agent-patch"


def github_publisher_node(state: AgentState) -> dict:
    """workspace_root の変更をブランチにコミット・プッシュし、PR を作成する。"""
    workspace_root = state.get("workspace_root") or "."
    generated_code = state.get("generated_code") or {}
    user_requirement = (state.get("user_requirement") or "")[:100]

    token = os.environ.get("GITHUB_TOKEN")
    repo_full = os.environ.get("GITHUB_REPOSITORY")  # e.g. owner/repo

    if not token or not repo_full:
        return {
            "status": "published",
            "pr_url": "",
            "error_logs": list(state.get("error_logs") or []) + [
                "GITHUB_TOKEN or GITHUB_REPOSITORY not set; skip PR creation"
            ],
        }

    work_dir = Path(workspace_root)
    branch_name = "agent/" + _sanitize_branch_name(user_requirement or "patch")
    error_logs = list(state.get("error_logs") or [])

    # 1) ローカルで git ブランチ作成・コミット・プッシュ（サンドボックス内実行前提）
    if (work_dir / ".git").exists():
        try:
            subprocess.run(
                ["git", "checkout", "-b", branch_name],
                cwd=work_dir,
                check=True,
                capture_output=True,
                text=True,
                timeout=30,
            )
            # 生成されたファイルを add（review ノードで既に書き出し済み）
            for rel in generated_code:
                p = work_dir / rel.replace("\\", "/")
                if p.exists():
                    subprocess.run(
                        ["git", "add", str(p)],
                        cwd=work_dir,
                        check=True,
                        capture_output=True,
                        timeout=10,
                    )
            subprocess.run(
                ["git", "commit", "-m", f"Agent: {user_requirement[:72]}"],
                cwd=work_dir,
                capture_output=True,
                text=True,
                timeout=10,
            )
            # remote に push（HTTPS + token）
            remote_url = f"https://{token}@github.com/{repo_full}.git"
            subprocess.run(
                ["git", "push", remote_url, f"HEAD:{branch_name}"],
                cwd=work_dir,
                capture_output=True,
                text=True,
                timeout=60,
                env={**os.environ, "GIT_TERMINAL_PROMPT": "0"},
            )
        except subprocess.CalledProcessError as e:
            error_logs.append(f"git error: {e.stderr or e.stdout or str(e)}")
            return {"status": "failed", "pr_url": "", "error_logs": error_logs}
        except Exception as e:
            error_logs.append(str(e))
            return {"status": "failed", "pr_url": "", "error_logs": error_logs}
    else:
        error_logs.append("workspace_root is not a git repo; cannot push")
        return {"status": "failed", "pr_url": "", "error_logs": error_logs}

    # 2) PR 作成（PyGithub）
    try:
        from github import Github

        gh = Github(token)
        repo = gh.get_repo(repo_full)
        pr = repo.create_pull(
            title=f"Agent: {user_requirement[:80]}",
            body="Auto-generated by Unicorn Agent. Please review before merge.",
            head=branch_name,
            base=repo.default_branch,
        )
        pr_url = pr.html_url or ""
    except ImportError:
        pr_url = f"https://github.com/{repo_full}/compare/{branch_name}"
        error_logs.append("PyGithub not installed; open URL above to create PR manually")
    except Exception as e:
        error_logs.append(f"create_pull: {e}")
        pr_url = f"https://github.com/{repo_full}/compare/{branch_name}"

    return {
        "status": "published",
        "pr_url": pr_url,
    }
