"""Pydantic models for proactive analysis."""
from typing import Optional
from uuid import UUID

from pydantic import BaseModel, Field


class ImpactEstimate(BaseModel):
    time_saved_hours: float | None = None
    cost_reduction_yen: int | None = None
    risk_reduction: float | None = Field(None, ge=0, le=1)
    confidence: float = Field(ge=0, le=1)
    calculation_basis: str | None = None


class Signal(BaseModel):
    source: str  # knowledge, state, log
    value: str
    score: float = Field(ge=0, le=1)


class Evidence(BaseModel):
    signals: list[Signal]


class Proposal(BaseModel):
    """A single proactive proposal generated by LLM analysis."""
    proposal_type: str  # risk_alert, improvement, rule_challenge, opportunity
    title: str
    description: str
    impact_estimate: ImpactEstimate | None = None
    evidence: Evidence | None = None
    priority: str = "medium"  # high, medium, low
    related_knowledge_ids: list[UUID] = []


class ProactiveAnalysisResult(BaseModel):
    """Result of a proactive analysis run."""
    proposals: list[Proposal]
    model_used: str
    cost_yen: float
    knowledge_count: int  # how many items were analyzed
